---
version: "3"

services:
  server:
    image: "node:11.1.0"
    volumes:
      - "./:/app"
    working_dir: "/app"
    environment:
      - "NODE_ENV=development"
    ports:
      - "8443:443"
    command: "node --experimental-modules --loader ./loader.mjs ./dist/main.js"
  psql:
    build: ./postgres/
    environment:
      POSTGRES_PASSWORD: "password"
    expose:
      - "5432"

...